name=str(input("ENTER NAME"))
principal = float(input("Enter amount "))
rate_in = float(input("Enter rate of interest "))
period = float(input("Enter time "))
Simple_int =(principal * rate_in * period )/100
print("Welcome to the Simple interest Calculator " + name)
print("*****************************************************************")
print("_________________________________________________________________")
print("*****************************************************************")
print("_________________________________________________________________")
print("Please wait Calculating your Simple interest" + name)
print("*****************************************************************")
print("_________________________________________________________________")
print("*****************************************************************")
print("_________________________________________________________________")
print("YOUR SIMPLE INTEREST HAS BEEN PRINTED BELOW FROM THE INFORMATION YOU GAVE US")
print(Simple_int)
print("the extra earnings are - " )
print(Simple_int - principal)